window.BUILTIN_STRINGS = {
  "en": {
    "appTitle": "На лов за Копейкин",
    "appTagline": "Kopeikin IP Hunt: proper procedure vs. shortcuts.",
    "language": "Language",
    "settings": "Settings",
    "notificationsTitle": "Notifications",
    "notificationsClear": "Clear",
    "notificationsEmpty": "No notifications yet.",
    "needsFirst": "Do this first:",
    "start": "Start New Case",
    "continue": "Continue",
    "howto": "How to Play",
    "reset": "Reset Save",
    "noSave": "No saved case in progress.",
    "howtoTitle": "How to Play",
    "howtoBody": "You are a junior clerk handling the Kopeikin file. Build a lawful request stack under pressure. Shortcuts are faster until they collapse.",
    "gotIt": "Got it",
    "settingsTitle": "Settings",
    "highContrast": "High contrast",
    "reduceMotion": "Reduce motion",
    "fontSize": "Font size",
    "back": "Back",
    "caseDrawTitle": "New Case Brief",
    "caseDrawSub": "The Kopeikin file lands on your desk with a loud thud.",
    "caseOpen": "Open the file",
    "caseSwap": "Swap scenario (costs time)",
    "caseHeader": "Case File",
    "caseService": "Service type",
    "caseJur": "Jurisdiction",
    "caseGoal": "Requested outcome",
    "casePressure": "Political pressure",
    "caseEmergency": "Emergency legally possible",
    "caseSerious": "Serious intentional crime context",
    "caseJudge": "Judge personality",
    "caseOperator": "Operator personality",
    "caseHint": "Hint: pressure says 'find Kopeikin's IP fast,' but legal scope still controls every step.",
    "toWorkbench": "Go to Workbench",
    "wbHeader": "Workbench",
    "meters": "Meters",
    "legality": "Legality",
    "trust": "Public trust",
    "time": "Time left",
    "audit": "Audit risk",
    "inventory": "Inventory",
    "workflow": "Workflow",
    "actions": "Actions",
    "status": "Status",
    "classifyAct": "Classify request",
    "instrumentAct": "Choose instrument",
    "draftAct": "Draft motivated request",
    "prosAct": "Call supervising prosecutor",
    "judgeAct": "Submit to judge",
    "serveAct": "Serve operator",
    "waitAct": "Wait for response",
    "reviewAct": "Review data + minimise",
    "shortcutAct": "Try shortcut",
    "finalizeAct": "Close file",
    "classifyTitle": "Classify the data source",
    "classifyISP": "ISP/telecom retained traffic data",
    "classifyPlatform": "Online platform logs",
    "classifyWild": "Send a ministerial letter (bad idea)",
    "confirm": "Confirm",
    "platformTitle": "Platform Path",
    "platformChoose": "Choose instrument",
    "platformDomestic": "Domestic production/preservation order",
    "platformEIO": "European Investigation Order (EIO)",
    "platformEE": "EU e-Evidence Order",
    "platformLetter": "Ministerial letter (illegal shortcut)",
    "platformNote": "Platforms are not automatically telecom operators. Procedure differs.",
    "appliesFrom": "e-Evidence application date",
    "prosRefused": "Prosecutor refused: threshold not met.",
    "prosOk": "Prosecutor memo prepared.",
    "judgeTitle": "District Court Desk",
    "judgeMonths": "Requested period (months)",
    "judgeMax": "Maximum 6 months.",
    "judgeNoPros": "Refused: no prosecutor-to-judge chain.",
    "judgeWide": "Refused: period is outside legal scope.",
    "judgeMis": "Refused: data source classification is defective.",
    "judgeNonSerious": "Refused: offence threshold not met.",
    "judgeBadInstrument": "Refused: selected instrument is incompatible.",
    "judgeOk": "Approved: order issued (razporezhdane).",
    "opMissing": "Reply: missing or invalid authorisation.",
    "opOk": "Reply received. Time zone and scope accepted.",
    "opDelay": "Reply delayed: package returned for clarifications.",
    "reviewTitle": "Data Review",
    "reviewBody": "Keep only relevant data. Everything else is liability.",
    "reviewKeep": "Keep relevant only",
    "reviewAll": "Keep everything (bad)",
    "destroyTitle": "Destruction",
    "destroyBody": "Irrelevant data must be destroyed and documented.",
    "destroyNow": "Destroy now",
    "destroySkip": "Skip (bad)",
    "destroyDone": "Destruction completed. Protocol logged.",
    "shortcutTitle": "Shortcut Options",
    "scNoOrder": "Ask without court order",
    "scFakeUrgent": "Mark as emergency (even if not)",
    "scPressure": "Pressure operator informally",
    "scFail": "Shortcut attempted. Consequences pending...",
    "event": "Event",
    "evJudge": "Judge is at a seminar. Processing delayed.",
    "evTimezone": "Operator asks: 'Which time zone is your timestamp in?'",
    "evLeak": "A confidential draft appears online. Trust drops.",
    "evOversight": "Oversight ping: 'Where is the register entry?'",
    "evEu": "EU-law alarm: retention model challenged.",
    "evEmergency": "Boss whispers: 'Call it an emergency.'",
    "empty": "(empty)",
    "yes": "Yes",
    "no": "No",
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "serviceISP": "ISP / Telecom",
    "servicePlatform": "Online Platform",
    "serviceHybrid": "Ambiguous Hybrid",
    "jurBG": "Bulgaria",
    "jurEU": "Cross-border EU",
    "jurThird": "Outside EU",
    "judgeFormalist": "Formalist",
    "judgePragmatist": "Pragmatist",
    "judgeEuNerd": "EU-law nerd",
    "judgeLunch": "Lunch break champion",
    "opStrict": "Strict KYC",
    "opFast": "Fast lane (if forms are perfect)",
    "opPort": "Port-number stickler",
    "docCase": "Case File Number",
    "docComp": "Competence Checklist",
    "docMot": "Motivated Request Form",
    "docPros": "Prosecutor Request Memo",
    "docCourt": "Judge's Order",
    "docServe": "Service Receipt",
    "docPacket": "Operator Response Packet",
    "docDestroy": "Destruction Protocol",
    "docReg": "Register Entry Stamp",
    "wfClassify": "Classify request",
    "wfInstrument": "Choose platform instrument",
    "wfDraft": "Draft motivated request",
    "wfPros": "Prosecutor gate",
    "wfJudge": "Judge authorisation",
    "wfServe": "Serve operator/platform",
    "wfWait": "Await response",
    "wfReview": "Review + minimise",
    "wfDestroy": "Destruction protocol",
    "done": "Done",
    "pending": "Pending",
    "failed": "Failed",
    "outcome": "Outcome",
    "copyShare": "Copy share text",
    "playAgain": "Play again",
    "menuBack": "Back to menu",
    "recommended": "Recommended",
    "hoursAbbr": "h",
    "minutesAbbr": "m",
    "eRuleTitle": "Rule of Law Any%",
    "eRuleBody": "You followed procedure and documented every step. Nobody clapped, but the file is clean.",
    "eRuleShare": "I followed procedure. The memes survived. Democracy too.",
    "eFaceTitle": "Procedural Faceplant",
    "eFaceBody": "You were close, but a mandatory element failed.",
    "eFaceShare": "Rejected for missing field 4. Bureaucracy 1, me 0.",
    "eScandalTitle": "Shortcut Scandal",
    "eScandalBody": "You got speed, not legitimacy. Enjoy audits and headlines.",
    "eScandalShare": "Speedrun strats: ministerial letter. Outcome: national embarrassment.",
    "eEuTitle": "EU-law Plot Twist",
    "eEuBody": "Domestic procedure succeeded, then higher-law safeguards triggered a challenge.",
    "eEuShare": "I did it by the book. Then the book got reviewed by Luxembourg.",
    "copied": "Share text copied to clipboard.",
    "copyFail": "Clipboard blocked.",
    "caseTarget": "Target",
    "caseKickoff": "Case opened: parliamentary reply triggered an IP hunt for Kopeikin admin.",
    "caseContextTitle": "News Context",
    "caseContext1": "A ministerial reply publicly confirmed an active search for Kopeikin admin IP data.",
    "caseContext2": "The parliamentary question reportedly did not name pages; the official reply spotlighted Kopeikin.",
    "caseContext3": "The story triggered a meme wave and mock headlines across social media.",
    "caseContext4": "The admin claims reposting a clip is a pretext for identity pressure, not a real legal need.",
    "caseContext5": "Public support followed: legal-help offers and crowdfunding boosts.",
    "evNameDrop": "Official reply explicitly names Kopeikin. Selective-targeting criticism spikes.",
    "evMemeStorm": "Meme storm: fake headlines and parody posts flood the feed.",
    "evSupportWave": "Support wave: followers and legal volunteers rally around Kopeikin.",
    "evSelectiveTarget": "Analysts ask why dozens shared the clip, but only one page gets spotlighted.",
    "targetLogoAlt": "Kopeikin group logo",
    "startOver": "Start Over",
    "locFallback": "Using built-in language pack because lang.json could not be loaded."
  },
  "bg": {
    "appTitle": "На лов за Копейкин",
    "appTagline": "Лов на IP за Kopeikin: правилна процедура срещу преки пътища.",
    "language": "Език",
    "settings": "Настройки",
    "notificationsTitle": "Известия",
    "notificationsClear": "Изчисти",
    "notificationsEmpty": "Все още няма известия.",
    "needsFirst": "Първо направи:",
    "start": "Нов случай",
    "continue": "Продължи",
    "howto": "Как се играе",
    "reset": "Изтрий записа",
    "noSave": "Няма запазен текущ случай.",
    "howtoTitle": "Как се играе",
    "howtoBody": "Ти си младши деловодител. Подготви законосъобразна документация под натиск. Преките пътища са бързи, докато не гръмнат.",
    "gotIt": "Ясно",
    "settingsTitle": "Настройки",
    "highContrast": "Висок контраст",
    "reduceMotion": "Намалена анимация",
    "fontSize": "Размер на шрифта",
    "back": "Назад",
    "caseDrawTitle": "Служебна преписка",
    "caseDrawSub": "Папка пада на бюрото ти с драматичен звук.",
    "caseOpen": "Отвори папката",
    "caseSwap": "Смени сценария (струва време)",
    "caseHeader": "Дело",
    "caseService": "Тип услуга",
    "caseJur": "Юрисдикция",
    "caseGoal": "Искан резултат",
    "casePressure": "Политически натиск",
    "caseEmergency": "Допустима спешност",
    "caseSerious": "Контекст: тежко умишлено престъпление",
    "caseJudge": "Стил на съдията",
    "caseOperator": "Стил на оператора",
    "caseHint": "Подсказка: IP адрес сам по себе си рядко идентифицира човек. Точният времеви обхват е решаващ.",
    "toWorkbench": "Към работното място",
    "wbHeader": "Работно място",
    "meters": "Показатели",
    "legality": "Законност",
    "trust": "Обществено доверие",
    "time": "Оставащо време",
    "audit": "Риск от проверка",
    "inventory": "Инвентар",
    "workflow": "Процедура",
    "actions": "Действия",
    "status": "Статус",
    "classifyAct": "Класифицирай искането",
    "instrumentAct": "Избери инструмент",
    "draftAct": "Изготви мотивирано искане",
    "prosAct": "Свържи се с наблюдаващ прокурор",
    "judgeAct": "Внеси при съдия",
    "serveAct": "Връчи на оператор",
    "waitAct": "Изчакай отговор",
    "reviewAct": "Преглед + минимизация",
    "shortcutAct": "Пробвай пряк път",
    "finalizeAct": "Приключи преписката",
    "classifyTitle": "Класифицирай източника на данни",
    "classifyISP": "Трафични данни от доставчик/оператор",
    "classifyPlatform": "Логове от онлайн платформа",
    "classifyWild": "Министерско писмо (лоша идея)",
    "confirm": "Потвърди",
    "platformTitle": "Път през платформа",
    "platformChoose": "Избери инструмент",
    "platformDomestic": "Вътрешна заповед за предаване/запазване",
    "platformEIO": "Европейска заповед за разследване (EIO)",
    "platformEE": "EU e-Evidence заповед",
    "platformLetter": "Министерско писмо (незаконен пряк път)",
    "platformNote": "Платформите не са автоматично оператори по телекомуникационния ред.",
    "appliesFrom": "Дата на приложение на e-Evidence",
    "prosRefused": "Отказ от прокурора: прагът не е покрит.",
    "prosOk": "Прокурорското искане е подготвено.",
    "judgeTitle": "Деловодство на районен съд",
    "judgeMonths": "Искан период (месеци)",
    "judgeMax": "Максимум 6 месеца.",
    "judgeNoPros": "Отказ: липсва прокурорско искане.",
    "judgeWide": "Отказ: периодът е извън допустимия обхват.",
    "judgeMis": "Отказ: грешна класификация на източника.",
    "judgeNonSerious": "Отказ: не е изпълнен прагът за тежко престъпление.",
    "judgeBadInstrument": "Отказ: избраният инструмент е несъвместим.",
    "judgeOk": "Разрешено: издадено разпореждане.",
    "opMissing": "Отговор: липсва/невалидно разрешение.",
    "opOk": "Получен отговор. Часовата зона и обхватът са приети.",
    "opDelay": "Забавяне: върнато за уточнения.",
    "reviewTitle": "Преглед на данните",
    "reviewBody": "Запази само свързаното. Останалото е риск.",
    "reviewKeep": "Само свързаното",
    "reviewAll": "Запази всичко (лошо)",
    "destroyTitle": "Унищожаване",
    "destroyBody": "Несвързаните данни трябва да се унищожат и документират.",
    "destroyNow": "Унищожи сега",
    "destroySkip": "Пропусни (лошо)",
    "destroyDone": "Унищожаването е извършено и протоколирано.",
    "shortcutTitle": "Преки пътища",
    "scNoOrder": "Искай без съдебно разпореждане",
    "scFakeUrgent": "Маркирай като спешно (без основание)",
    "scPressure": "Неформален натиск към оператора",
    "scFail": "Пробван е пряк път. Последствията идват...",
    "event": "Събитие",
    "evJudge": "Съдията е на семинар. Има забавяне.",
    "evTimezone": "Операторът пита: 'В коя часова зона е времето?'",
    "evLeak": "Поверителна чернова изтече онлайн. Доверието пада.",
    "evOversight": "Контролен сигнал: 'Къде е вписването в регистъра?'",
    "evEu": "EU сигнал: моделът за retention е оспорен.",
    "evEmergency": "Шефът шепне: 'Обяви го за спешно.'",
    "empty": "(празно)",
    "yes": "Да",
    "no": "Не",
    "low": "Нисък",
    "medium": "Среден",
    "high": "Висок",
    "serviceISP": "Доставчик / Оператор",
    "servicePlatform": "Онлайн платформа",
    "serviceHybrid": "Неясна хибридна услуга",
    "jurBG": "България",
    "jurEU": "Трансгранично в ЕС",
    "jurThird": "Извън ЕС",
    "judgeFormalist": "Формалист",
    "judgePragmatist": "Прагматик",
    "judgeEuNerd": "EU-право ентусиаст",
    "judgeLunch": "Шампион по обедна почивка",
    "opStrict": "Строга проверка",
    "opFast": "Бърза лента (само перфектни форми)",
    "opPort": "Педант за порт номер",
    "docCase": "Номер на преписката",
    "docComp": "Проверка за компетентност",
    "docMot": "Формуляр: мотивирано искане",
    "docPros": "Прокурорско искане",
    "docCourt": "Съдебно разпореждане",
    "docServe": "Разписка за връчване",
    "docPacket": "Пакет от оператора",
    "docDestroy": "Протокол за унищожаване",
    "docReg": "Печат за регистъра",
    "wfClassify": "Класификация",
    "wfInstrument": "Избор на инструмент",
    "wfDraft": "Мотивирано искане",
    "wfPros": "Прокурорски етап",
    "wfJudge": "Съдебно разрешение",
    "wfServe": "Връчване",
    "wfWait": "Изчакване",
    "wfReview": "Преглед и минимизация",
    "wfDestroy": "Протокол за унищожаване",
    "done": "Готово",
    "pending": "Чака",
    "failed": "Провал",
    "outcome": "Резултат",
    "copyShare": "Копирай текст за споделяне",
    "playAgain": "Играй пак",
    "menuBack": "Към менюто",
    "recommended": "Препоръчително",
    "hoursAbbr": "ч",
    "minutesAbbr": "м",
    "eRuleTitle": "Законност Any%",
    "eRuleBody": "Спази процедурата и документира всичко. Никой не ръкопляска, но делото е чисто.",
    "eRuleShare": "Спазих процедурата. Меметата оцеляха. И демокрацията също.",
    "eFaceTitle": "Процедурен фал",
    "eFaceBody": "Беше близо, но липсваше задължителен елемент.",
    "eFaceShare": "Върнато за липсващ реквизит. Бюрокрация 1, аз 0.",
    "eScandalTitle": "Скандал с пряк път",
    "eScandalBody": "Скорост има, легитимност няма. Следват проверки и заглавия.",
    "eScandalShare": "Speedrun: министерско писмо. Резултат: национален резил.",
    "eEuTitle": "EU сюжетен обрат",
    "eEuBody": "Спазен е вътрешният ред, но по-високите гаранции отключиха спор.",
    "eEuShare": "Направих го по правилата. После правилата ги прегледаха в Люксембург.",
    "copied": "Текстът е копиран.",
    "copyFail": "Клипбордът е блокиран.",
    "caseTarget": "Цел",
    "caseKickoff": "Случаят е отворен: парламентарен отговор отприщи издирване на IP на администратора на Kopeikin.",
    "caseContextTitle": "Контекст от новините",
    "caseContext1": "В парламентарен отговор публично беше потвърдено търсене на IP данни за администратора на Kopeikin.",
    "caseContext2": "Според публикации въпросът не е назовал страници, но официалният отговор насочва прожектора към Kopeikin.",
    "caseContext3": "Случаят отприщи вълна от мемета, шеги и сатирични заглавия в мрежата.",
    "caseContext4": "Администраторът твърди, че споделен клип е използван като претекст за натиск и разкриване на самоличност.",
    "caseContext5": "Появи се и подкрепа: предложения за pro bono правна помощ и ръст на дарителите.",
    "evNameDrop": "В официален отговор Kopeikin е назован директно. Критиките за избирателно таргетиране се усилват.",
    "evMemeStorm": "Меме буря: фалшиви заглавия и пародийни постове заливат емисията.",
    "evSupportWave": "Вълна от подкрепа: последователи и доброволни юристи застават зад Kopeikin.",
    "evSelectiveTarget": "Анализатори питат защо десетки споделят клипа, а прожекторът остава само върху една страница.",
    "targetLogoAlt": "Лого на групата Kopeikin",
    "startOver": "\u0417\u0430\u043f\u043e\u0447\u043d\u0438 \u043e\u0442\u043d\u0430\u0447\u0430\u043b\u043e",
    "locFallback": "\u0418\u0437\u043f\u043e\u043b\u0437\u0432\u0430 \u0441\u0435 \u0432\u0433\u0440\u0430\u0434\u0435\u043d \u0435\u0437\u0438\u043a\u043e\u0432 \u043f\u0430\u043a\u0435\u0442, \u0437\u0430\u0449\u043e\u0442\u043e lang.json \u043d\u0435 \u043c\u043e\u0436\u0435 \u0434\u0430 \u0441\u0435 \u0437\u0430\u0440\u0435\u0434\u0438."
  }
};
