// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ivone.dev.Data.Contexts;

#nullable disable

namespace Ivone.dev.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116150542_AddTimelineEventMetadata")]
    partial class AddTimelineEventMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "London"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Manchester"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Belfast"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "Cardiff"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "16"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "17"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "18"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "21"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Rose"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Thistle"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "Daffodil"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "Shamrock"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "William the Conqueror"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Henry VIII"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Elizabeth I"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Queen Victoria"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "1 January"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "14 February"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "5 November"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "25 December"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Euro"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "US Dollar"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = true,
                            QuestionId = 6,
                            Text = "Pound sterling"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuestionId = 6,
                            Text = "Swiss franc"
                        });
                });

            modelBuilder.Entity("Ivone.dev.Data.Models.RegionStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgPerSqm")
                        .HasColumnType("int");

                    b.Property<int?>("Price1")
                        .HasColumnType("int");

                    b.Property<int?>("Price1PerSqm")
                        .HasColumnType("int");

                    b.Property<int?>("Price2")
                        .HasColumnType("int");

                    b.Property<int?>("Price2PerSqm")
                        .HasColumnType("int");

                    b.Property<int?>("Price3")
                        .HasColumnType("int");

                    b.Property<int?>("Price3PerSqm")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegionStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgPerSqm = 2790,
                            Price1 = 310000,
                            Price1PerSqm = 3000,
                            Price2 = 285000,
                            Price2PerSqm = 2780,
                            Price3 = 255000,
                            Price3PerSqm = 2600,
                            Region = "Sofia Center",
                            StatDate = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AvgPerSqm = 2200,
                            Price1 = 235000,
                            Price1PerSqm = 2350,
                            Price2 = 210000,
                            Price2PerSqm = 2200,
                            Price3 = 190000,
                            Price3PerSqm = 2050,
                            Region = "Sofia South",
                            StatDate = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AvgPerSqm = 1970,
                            Price1 = 185000,
                            Price1PerSqm = 2150,
                            Price2 = 165000,
                            Price2PerSqm = 1950,
                            Price3 = 150000,
                            Price3PerSqm = 1820,
                            Region = "Studentski Grad",
                            StatDate = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MortgageScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LawyerFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LawyerFeeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanTermInYears")
                        .HasColumnType("int");

                    b.Property<decimal>("MortgageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ParkingSpotCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MortgageScenarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionAmount = 8550m,
                            CommissionRate = 3m,
                            Currency = "EUR",
                            DepositAmount = 57000m,
                            DepositPercentage = 20m,
                            LawyerFeeAmount = 3420m,
                            LawyerFeeRate = 1.2m,
                            LoanTermInYears = 30,
                            MortgageAmount = 228000m,
                            Name = "Two Bedroom • City Center",
                            ParkingSpotCost = 20000m,
                            TotalCost = 285000m
                        },
                        new
                        {
                            Id = 2,
                            CommissionAmount = 4125m,
                            CommissionRate = 2.5m,
                            Currency = "EUR",
                            DepositAmount = 24750m,
                            DepositPercentage = 15m,
                            LawyerFeeAmount = 1650m,
                            LawyerFeeRate = 1m,
                            LoanTermInYears = 25,
                            MortgageAmount = 140250m,
                            Name = "Starter Flat • Sofia South",
                            ParkingSpotCost = 12000m,
                            TotalCost = 165000m
                        },
                        new
                        {
                            Id = 3,
                            CommissionAmount = 8820m,
                            CommissionRate = 2.8m,
                            Currency = "EUR",
                            DepositAmount = 78750m,
                            DepositPercentage = 25m,
                            LawyerFeeAmount = 4095m,
                            LawyerFeeRate = 1.3m,
                            LoanTermInYears = 30,
                            MortgageAmount = 236250m,
                            Name = "House + Parking • Suburbs",
                            ParkingSpotCost = 15000m,
                            TotalCost = 315000m
                        });
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Explanation = "London is the UK capital and seat of government.",
                            TestId = 1,
                            Text = "What is the capital city of the United Kingdom?"
                        },
                        new
                        {
                            Id = 2,
                            Explanation = "All UK citizens aged 18 or over can vote.",
                            TestId = 1,
                            Text = "What is the minimum age for voting in UK general elections?"
                        },
                        new
                        {
                            Id = 3,
                            Explanation = "The daffodil is widely used as the Welsh emblem.",
                            TestId = 1,
                            Text = "Which flower is the national emblem of Wales?"
                        },
                        new
                        {
                            Id = 4,
                            Explanation = "William the Conqueror began building the Tower in the 11th century.",
                            TestId = 2,
                            Text = "Who ordered the construction of the Tower of London?"
                        },
                        new
                        {
                            Id = 5,
                            Explanation = "Bonfire Night, or Guy Fawkes Night, is on 5 November.",
                            TestId = 2,
                            Text = "When is Bonfire Night celebrated in the UK?"
                        },
                        new
                        {
                            Id = 6,
                            Explanation = "The UK uses the pound sterling (GBP).",
                            TestId = 2,
                            Text = "What is the official currency of the United Kingdom?"
                        });
                });

            modelBuilder.Entity("Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Life in the UK • Core Facts"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Life in the UK • Traditions"
                        });
                });

            modelBuilder.Entity("Timeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Timelines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home Purchase Journey",
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("TimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatePrecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimelineId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TimelineId");

                    b.ToTable("TimelineEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Online + site visits",
                            Date = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Compare average price per sqm across districts.",
                            TimelineId = 1,
                            Title = "Research neighborhoods"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Local bank branch",
                            Date = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Prepare proof of income and savings statements.",
                            TimelineId = 1,
                            Title = "Bank pre-approval meeting"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Sofia South complex",
                            Date = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Tour sample apartment and parking layout.",
                            TimelineId = 1,
                            Title = "First developer visit"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFacebook")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoogle")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLinkedIn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@ivone.dev",
                            HasPaid = false,
                            IsFacebook = false,
                            IsGoogle = false,
                            IsLinkedIn = false,
                            IsLocal = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shared@ivone.dev",
                            HasPaid = true,
                            IsFacebook = false,
                            IsGoogle = true,
                            IsLinkedIn = true,
                            IsLocal = false
                        });
                });

            modelBuilder.Entity("UserTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TimelineId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimelineId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTimelines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TimelineId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            TimelineId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Answer", b =>
                {
                    b.HasOne("Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.HasOne("Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TimelineEvent", b =>
                {
                    b.HasOne("Timeline", "Timeline")
                        .WithMany("TimelineEvents")
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("UserTimeline", b =>
                {
                    b.HasOne("Timeline", "Timeline")
                        .WithMany("UserTimelines")
                        .HasForeignKey("TimelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timeline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Test", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Timeline", b =>
                {
                    b.Navigation("TimelineEvents");

                    b.Navigation("UserTimelines");
                });
#pragma warning restore 612, 618
        }
    }
}
